spring:
  application:
    name: user-service8092
  profiles:
    active: proud
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yaml
      discovery:
        server-addr: localhost:8848
  config:
    import: "nacos:${spring.application.name}-${spring.profiles.active}.yaml?refresh=true"
server:
  port: 8092
