spring:
  application:
    name: order-consumer8091
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yaml
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      eager: true
  config:
    import: "nacos:${spring.application.name}-${spring.profiles.active}.yaml?refresh=true"
server:
  port: 8091

rocketmq:
  name-server: localhost:9876
  producer:
    group: order-producer-group
